[build]
  command = "npm run build" # Adjust if no build step
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
